# Generated by Django 4.2.7 on 2025-09-29 19:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('entidad_tipo', models.CharField(choices=[('VIVIENDA', 'Vivienda'), ('AREA_COMUN', 'Área Común')], max_length=20, verbose_name='Tipo de entidad')),
                ('entidad_id', models.IntegerField(verbose_name='ID de la entidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('urgente', 'Urgente')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='solicitado', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo de materiales')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo de mano de obra')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('garantia_meses', models.IntegerField(blank=True, null=True, verbose_name='Garantía (meses)')),
                ('evidencia_antes', models.URLField(blank=True, null=True, verbose_name='Evidencia antes')),
                ('evidencia_despues', models.URLField(blank=True, null=True, verbose_name='Evidencia después')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
