# Generated by Django 4.2.7 on 2025-09-29 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('puerto', models.IntegerField(default=80, verbose_name='Puerto')),
                ('usuario_camara', models.CharField(blank=True, max_length=50, verbose_name='Usuario')),
                ('password_camara', models.CharField(blank=True, max_length=100, verbose_name='Contraseña')),
                ('url_stream', models.URLField(verbose_name='URL de streaming')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('resolucion', models.CharField(blank=True, max_length=20, verbose_name='Resolución')),
                ('vision_nocturna', models.BooleanField(default=False, verbose_name='Visión nocturna')),
                ('angulo_vision', models.IntegerField(blank=True, null=True, verbose_name='Ángulo de visión')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('severidad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=1, verbose_name='Severidad')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('parqueadero', 'Parqueadero'), ('lobby', 'Lobby'), ('piscina', 'Piscina'), ('gimnasio', 'Gimnasio'), ('salon', 'Salón Social')], max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nivel_seguridad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20, verbose_name='Nivel de seguridad')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='VehiculoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('bicicleta', 'Bicicleta')], max_length=20, verbose_name='Tipo de vehículo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vehículo Autorizado',
                'verbose_name_plural': 'Vehículos Autorizados',
            },
        ),
        migrations.CreateModel(
            name='EventoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('evidencia_url', models.URLField(blank=True, null=True, verbose_name='URL de evidencia')),
                ('severidad', models.IntegerField(default=1, verbose_name='Severidad')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('notas_resolucion', models.TextField(blank=True, null=True, verbose_name='Notas de resolución')),
                ('camara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.camara', verbose_name='Cámara')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.tipoevento', verbose_name='Tipo de evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo_autorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.vehiculoautorizado', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Evento de Seguridad',
                'verbose_name_plural': 'Eventos de Seguridad',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CredentialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('identificador', models.CharField(max_length=100, verbose_name='Identificador')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('pin', 'PIN'), ('biometrico', 'Biométrico'), ('app', 'Aplicación')], max_length=20, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('vencido', 'Vencido')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo_autorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.vehiculoautorizado', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Credencial de Acceso',
                'verbose_name_plural': 'Credenciales de Acceso',
            },
        ),
        migrations.AddField(
            model_name='camara',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.zona', verbose_name='Zona'),
        ),
    ]
