# Generated by Django 4.2.7 on 2025-09-29 19:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('periodo_mes', models.IntegerField(verbose_name='Mes del período')),
                ('periodo_ano', models.IntegerField(verbose_name='Año del período')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('interes_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Interés por mora (%)')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'unique_together': {('vivienda', 'periodo_mes', 'periodo_ano')},
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('requiere_comprobante', models.BooleanField(default=False, verbose_name='Requiere comprobante')),
                ('verificacion_automatica', models.BooleanField(default=False, verbose_name='Verificación automática')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('numero_referencia', models.CharField(blank=True, max_length=100, verbose_name='Número de referencia')),
                ('comprobante_url', models.URLField(blank=True, null=True, verbose_name='Comprobante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.deuda', verbose_name='Deuda')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.tipopago', verbose_name='Tipo de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='DetalleDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('concepto', models.CharField(max_length=100, verbose_name='Concepto')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('periodo_consumo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Período de consumo')),
                ('base_calculo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Base de cálculo')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payments.deuda', verbose_name='Deuda')),
            ],
            options={
                'verbose_name': 'Detalle de Deuda',
                'verbose_name_plural': 'Detalles de Deuda',
            },
        ),
    ]
