# Generated by Django 5.0 on 2025-09-30 22:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable'), ('extraordinario', 'Extraordinario')], default='fijo', max_length=20, verbose_name='Tipo')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor base')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Es obligatorio')),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unica', 'Única vez')], default='mensual', max_length=20, verbose_name='Frecuencia')),
                ('aplica_a_todos', models.BooleanField(default=True, verbose_name='Aplica a todas las viviendas')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('criterios_aplicacion', models.JSONField(blank=True, default=dict, verbose_name='Criterios de aplicación')),
                ('porcentaje_interes_mora', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Porcentaje interés mora')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('requiere_referencia', models.BooleanField(default=False, verbose_name='Requiere referencia')),
                ('requiere_comprobante', models.BooleanField(default=False, verbose_name='Requiere comprobante')),
                ('configuracion', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Comisión (%)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='comprobante_url',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='deuda',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_verificacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='verificado_por',
        ),
        migrations.AddField(
            model_name='pago',
            name='archivo_comprobante',
            field=models.URLField(blank=True, null=True, verbose_name='Archivo comprobante'),
        ),
        migrations.AddField(
            model_name='pago',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_reverso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reverso'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_reverso',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo del reverso'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_pago',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Número de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='reversado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reversados', to=settings.AUTH_USER_MODEL, verbose_name='Reversado por'),
        ),
        migrations.AddField(
            model_name='pago',
            name='vivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('reversado', 'Reversado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(verbose_name='Fecha de pago'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('periodo', models.CharField(max_length=7, verbose_name='Periodo (YYYY-MM)')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de generación')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto original')),
                ('descuentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuentos')),
                ('intereses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Intereses por mora')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('pendiente', 'Pendiente'), ('parcialmente_pagada', 'Parcialmente Pagada'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='generada', max_length=20, verbose_name='Estado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.URLField(blank=True, null=True, verbose_name='Archivo PDF')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='payments.conceptopago', verbose_name='Concepto')),
                ('generada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generada por')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_generacion'],
                'unique_together': {('vivienda', 'concepto', 'periodo')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.metodopago', verbose_name='Método de pago'),
        ),
        migrations.CreateModel(
            name='PazYSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('fecha_corte', models.DateTimeField(verbose_name='Fecha de corte')),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de generación')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo pendiente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_pdf', models.URLField(blank=True, null=True, verbose_name='Archivo PDF')),
                ('codigo_verificacion', models.CharField(max_length=50, unique=True, verbose_name='Código de verificación')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Paz y Salvo',
                'verbose_name_plural': 'Paz y Salvos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto aplicado')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aplicación')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.factura', verbose_name='Factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Pago Factura',
                'verbose_name_plural': 'Pagos Facturas',
                'unique_together': {('pago', 'factura')},
            },
        ),
    ]
