# Generated by Django 4.2.7 on 2025-09-29 19:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad (personas)')),
                ('capacidad_vehiculos', models.IntegerField(blank=True, null=True, verbose_name='Capacidad de vehículos')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora')),
                ('precio_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por día')),
                ('servicios_incluidos', models.JSONField(blank=True, default=list, verbose_name='Servicios incluidos')),
                ('normas_uso', models.TextField(blank=True, verbose_name='Normas de uso')),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Depósito de garantía')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('tipo_reserva', models.CharField(choices=[('por_horas', 'Por horas'), ('por_dias', 'Por días'), ('eventos', 'Eventos')], max_length=20, verbose_name='Tipo de reserva')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto pagado')),
                ('metodo_pago', models.CharField(blank=True, max_length=30, null=True, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo_evento', models.CharField(blank=True, max_length=200, verbose_name='Motivo del evento')),
                ('numero_personas', models.IntegerField(blank=True, null=True, verbose_name='Número de personas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_areas.areacomun', verbose_name='Área común')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_areas.areacomun', verbose_name='Área común')),
            ],
            options={
                'verbose_name': 'Horario de Área',
                'verbose_name_plural': 'Horarios de Áreas',
                'unique_together': {('area_comun', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
