# Generated by Django 4.2.7 on 2025-09-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='capacidad_vehiculos',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='deposito_garantia',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='foto_url',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='precio_dia',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='precio_hora',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='servicios_incluidos',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='tipo_reserva',
        ),
        migrations.AddField(
            model_name='areacomun',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Área Activa'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad Máxima'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='dias_anticipacion_max',
            field=models.PositiveIntegerField(default=30, verbose_name='Días Máximos de Anticipación para Reservar'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='dias_anticipacion_min',
            field=models.PositiveIntegerField(default=1, verbose_name='Días Mínimos de Anticipación para Reservar'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='equipamiento',
            field=models.JSONField(blank=True, default=list, verbose_name='Equipamiento Incluido'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='horario_fin',
            field=models.TimeField(default='00:00', verbose_name='Horario de Cierre'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='horario_inicio',
            field=models.TimeField(default='00:00', verbose_name='Horario de Apertura'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='imagen_principal',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de Imagen Principal'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='imagenes',
            field=models.JSONField(blank=True, default=list, verbose_name='Galería de Imágenes'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='requiere_pago',
            field=models.BooleanField(default=False, verbose_name='Requiere Pago'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tarifa_uso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa de Uso'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tiempo_maximo_reserva',
            field=models.PositiveIntegerField(default=4, verbose_name='Tiempo Máximo de Reserva (horas)'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tiempo_minimo_reserva',
            field=models.PositiveIntegerField(default=1, verbose_name='Tiempo Mínimo de Reserva (horas)'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tipo',
            field=models.CharField(choices=[('salon_eventos', 'Salón de Eventos'), ('piscina', 'Piscina'), ('gimnasio', 'Gimnasio'), ('bbq', 'Zona BBQ'), ('deportiva', 'Área Deportiva'), ('juegos', 'Sala de Juegos'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Área'),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='normas_uso',
            field=models.JSONField(blank=True, default=list, verbose_name='Normas de Uso'),
        ),
    ]
