# Generated by Django 4.2.7 on 2025-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
