# Generated by Django 4.2.7 on 2025-09-29 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('tabla', models.CharField(blank=True, max_length=100, verbose_name='Tabla afectada')),
                ('id_registro_afectado', models.CharField(blank=True, max_length=50, verbose_name='ID del registro')),
                ('ip_origen', models.GenericIPAddressField(verbose_name='IP de origen')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditoría de Usuarios',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
