# Generated by Django 4.2.7 on 2025-09-29 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('identificador', models.CharField(max_length=20, unique=True, verbose_name='Identificador')),
                ('bloque', models.CharField(blank=True, max_length=10, verbose_name='Bloque')),
                ('piso', models.IntegerField(blank=True, null=True, verbose_name='Piso')),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('local', 'Local')], max_length=20, verbose_name='Tipo')),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Metros cuadrados')),
                ('habitaciones', models.IntegerField(default=0, verbose_name='Habitaciones')),
                ('banos', models.IntegerField(default=0, verbose_name='Baños')),
                ('cuota_administracion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota de administración')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario_inquilino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viviendas_alquiler', to=settings.AUTH_USER_MODEL, verbose_name='Inquilino')),
                ('usuario_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viviendas_propiedad', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
            },
        ),
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Persona Autorizada',
                'verbose_name_plural': 'Personas Autorizadas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('vacunas_al_dia', models.BooleanField(default=False, verbose_name='Vacunas al día')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
